/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package callcenter;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dell
 */
public class MyAccount extends javax.swing.JDialog {

    String name, username;
    Connection connection;
    CardLayout c = new CardLayout();

    /**
     * Creates new form MyAccount
     */
    public MyAccount(java.awt.Frame parent, boolean modal, String name, String username, Connection connection) {
        super(parent, modal);
        initComponents();
        this.name = name;
        this.username = username;
        this.connection = connection;
        nameL.setText(name);
        usernameL.setText(username);
        accountBaseP.setLayout(c);
        accountBaseP.add(accountFirstP, "first");
        accountBaseP.add(accountSecondP, "second");
        errorL.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountBaseP = new javax.swing.JPanel();
        accountFirstP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernameL = new javax.swing.JLabel();
        nameL = new javax.swing.JLabel();
        changeB = new javax.swing.JButton();
        accountSecondP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newpassP = new javax.swing.JPasswordField();
        confirmpassP = new javax.swing.JPasswordField();
        currentpassP = new javax.swing.JPasswordField();
        resetB = new javax.swing.JButton();
        submitB = new javax.swing.JButton();
        backB = new javax.swing.JButton();
        errorL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(377, 290));
        setMinimumSize(new java.awt.Dimension(377, 290));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(377, 290));
        getContentPane().setLayout(null);

        accountBaseP.setMaximumSize(new java.awt.Dimension(377, 290));
        accountBaseP.setMinimumSize(new java.awt.Dimension(377, 290));
        accountBaseP.setName(""); // NOI18N
        accountBaseP.setPreferredSize(new java.awt.Dimension(377, 290));
        accountBaseP.setLayout(null);

        accountFirstP.setMaximumSize(new java.awt.Dimension(377, 290));
        accountFirstP.setMinimumSize(new java.awt.Dimension(377, 290));
        accountFirstP.setName(""); // NOI18N
        accountFirstP.setPreferredSize(new java.awt.Dimension(377, 290));
        accountFirstP.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Your Current Details");
        accountFirstP.add(jLabel2);
        jLabel2.setBounds(20, 0, 250, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("UserName");
        accountFirstP.add(jLabel4);
        jLabel4.setBounds(20, 90, 70, 25);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Name");
        accountFirstP.add(jLabel6);
        jLabel6.setBounds(20, 50, 60, 25);

        usernameL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        accountFirstP.add(usernameL);
        usernameL.setBounds(100, 90, 190, 25);

        nameL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        accountFirstP.add(nameL);
        nameL.setBounds(100, 50, 190, 25);

        changeB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        changeB.setText("Change Password");
        changeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBActionPerformed(evt);
            }
        });
        accountFirstP.add(changeB);
        changeB.setBounds(80, 150, 150, 30);

        accountBaseP.add(accountFirstP);
        accountFirstP.setBounds(0, 0, 340, 250);

        accountSecondP.setMaximumSize(new java.awt.Dimension(377, 290));
        accountSecondP.setMinimumSize(new java.awt.Dimension(377, 290));
        accountSecondP.setPreferredSize(new java.awt.Dimension(377, 290));
        accountSecondP.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Change Password");
        accountSecondP.add(jLabel1);
        jLabel1.setBounds(20, 10, 310, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("New Password");
        accountSecondP.add(jLabel3);
        jLabel3.setBounds(20, 90, 120, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("Confirm Password");
        accountSecondP.add(jLabel5);
        jLabel5.setBounds(20, 130, 120, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setText("Current Password");
        accountSecondP.add(jLabel7);
        jLabel7.setBounds(20, 50, 120, 30);
        accountSecondP.add(newpassP);
        newpassP.setBounds(150, 90, 170, 30);
        accountSecondP.add(confirmpassP);
        confirmpassP.setBounds(150, 130, 170, 30);
        accountSecondP.add(currentpassP);
        currentpassP.setBounds(150, 50, 170, 30);

        resetB.setText("Reset");
        resetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBActionPerformed(evt);
            }
        });
        accountSecondP.add(resetB);
        resetB.setBounds(150, 200, 73, 30);

        submitB.setText("Submit");
        submitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBActionPerformed(evt);
            }
        });
        accountSecondP.add(submitB);
        submitB.setBounds(60, 200, 73, 30);

        backB.setText("Back");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        accountSecondP.add(backB);
        backB.setBounds(240, 200, 55, 30);

        errorL.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        errorL.setForeground(new java.awt.Color(255, 0, 51));
        accountSecondP.add(errorL);
        errorL.setBounds(20, 170, 250, 20);

        accountBaseP.add(accountSecondP);
        accountSecondP.setBounds(0, 0, 340, 250);

        getContentPane().add(accountBaseP);
        accountBaseP.setBounds(0, 0, 340, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBActionPerformed
        // TODO add your handling code here:
        c.show(accountBaseP, "second");
    }//GEN-LAST:event_changeBActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        // TODO add your handling code here:
        c.show(accountBaseP, "first");
    }//GEN-LAST:event_backBActionPerformed

    public Boolean validateUser() {
        Boolean flag = true;
        if("".equals(currentpassP.getText()) || "".equals(newpassP.getText()) || "".equals(confirmpassP.getText())){
            flag = false;
            errorL.setText("Please enter all the fields!");
            errorL.setVisible(true);
        } else if(newpassP.getText()!=(confirmpassP.getText())){
            flag=false;
            errorL.setText("New and Confirm passowrd do not match!");
            errorL.setVisible(true);
        }else if(currentpassP.getText().equals(newpassP.getText())){
            flag = false;
            errorL.setText("Current password and new password cannot be same!");
        }
        else{
        try {
            Statement stm = connection.createStatement();
                    String q = "select password from user_details where username='" + username + "'";
            ResultSet rs = stm.executeQuery(q);
            while(rs.next()){
                String actual_pass = rs.getString("password");
                if(actual_pass.equals(currentpassP.getText())){
                    break;
                }
                else{
                      errorL.setText("Current Password is incorrect!");
                      errorL.setVisible(true);
                      flag = false;
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MyAccount.class.getName()).log(Level.SEVERE, null, ex);
            flag=false;
        }
        }

        
       
        return flag;
    }

    private void submitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBActionPerformed
        // TODO add your handling code here:
        Boolean flag = validateUser();
        if(flag==true){
        String password = confirmpassP.getText();
        String q = "update user_details set password='" + password + "' where username='" + username + "'";
    }//GEN-LAST:event_submitBActionPerformed
    }
    private void resetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBActionPerformed
        // TODO add your handling code here:
        currentpassP.setText("");
        newpassP.setText("");
        confirmpassP.setText("");
    }//GEN-LAST:event_resetBActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountBaseP;
    private javax.swing.JPanel accountFirstP;
    private javax.swing.JPanel accountSecondP;
    private javax.swing.JButton backB;
    private javax.swing.JButton changeB;
    private javax.swing.JPasswordField confirmpassP;
    private javax.swing.JPasswordField currentpassP;
    private javax.swing.JLabel errorL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nameL;
    private javax.swing.JPasswordField newpassP;
    private javax.swing.JButton resetB;
    private javax.swing.JButton submitB;
    private javax.swing.JLabel usernameL;
    // End of variables declaration//GEN-END:variables
}
